version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gh-lambda-app"
s3_bucket = "gha-lambda-jtest"
s3_prefix = "gh-lambda-app"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

